In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6], dtype=np.float64)

In [3]:
a.dtype

dtype('float64')

In [4]:
a[3], a[-2]

(4.0, 5.0)

In [5]:
a[2:-1]

array([3., 4., 5.])

In [6]:
a.dot(a)

91.0

In [7]:
a @ a

91.0

In [8]:
a.shape

(6,)

In [9]:
aa = a.reshape((3,2))
aa

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [10]:
aa.shape

(3, 2)

In [11]:
a.reshape((a.size,1))

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [12]:
v = a[:,np.newaxis]
v

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [13]:
a[np.newaxis,:]

array([[1., 2., 3., 4., 5., 6.]])

In [14]:
# should fail
v @ v

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 1)

In [15]:
v.T @ v

array([[91.]])

In [16]:
v @ v.T

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

In [17]:
np.einsum('i, j -> ij', a, a)

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

In [18]:
np.einsum('i, i', a, a)

91.0

In [19]:
M = np.random.randn(6,6)
M.dot(v)

array([[-3.65445443],
       [-5.86056354],
       [-7.77957503],
       [ 4.4556562 ],
       [-0.05471531],
       [-3.43735182]])

In [20]:
M @ a

array([-3.65445443, -5.86056354, -7.77957503,  4.4556562 , -0.05471531,
       -3.43735182])

In [21]:
M @ v

array([[-3.65445443],
       [-5.86056354],
       [-7.77957503],
       [ 4.4556562 ],
       [-0.05471531],
       [-3.43735182]])

In [22]:
np.einsum('ij, jk -> ik', M, v)

array([[-3.65445443],
       [-5.86056354],
       [-7.77957503],
       [ 4.4556562 ],
       [-0.05471531],
       [-3.43735182]])

In [23]:
np.einsum('ij, j -> i', M, a)

array([-3.65445443, -5.86056354, -7.77957503,  4.4556562 , -0.05471531,
       -3.43735182])

In [24]:
a>2

array([False, False,  True,  True,  True,  True])

In [25]:
cond = np.logical_and(a>2, a<5)

In [26]:
cond

array([False, False,  True,  True, False, False])

In [27]:
cond.astype(np.int32)

array([0, 0, 1, 1, 0, 0])

In [28]:
cond.sum()

2

In [29]:
a[cond]

array([3., 4.])

In [30]:
a.shape, cond.shape

((6,), (6,))

In [31]:
a[a>2]

array([3., 4., 5., 6.])

In [32]:
(a>2).sum()

4

In [33]:
b = a[:-1] # it's NOT a copy
b

array([1., 2., 3., 4., 5.])

In [34]:
b[:] = 99

In [35]:
b

array([99., 99., 99., 99., 99.])

In [36]:
a

array([99., 99., 99., 99., 99.,  6.])

In [37]:
c = a.copy()
c

array([99., 99., 99., 99., 99.,  6.])

In [38]:
c[0] = 77
c

array([77., 99., 99., 99., 99.,  6.])

In [39]:
a

array([99., 99., 99., 99., 99.,  6.])

In [40]:
d = dict()
d['pi'] = 3.14
for k in d: print (k,d[k])

pi 3.14


In [41]:
d[0] = 'test'

In [42]:
d

{'pi': 3.14, 0: 'test'}